name: Robot Framework Tests

on:
  push:
    branches:
      - main

jobs:
  selenium_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up directories
        run: |
          mkdir tests sources sources/frontend sources/backend sources/db
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: sources/frontend
      - name: Retrieve tests
        run: |
          git clone https://github.com/DevOps-2023-TeamA/tsao-tests.git tests/alltests
          cp -r tests/alltests/frontend/* tests
        working-directory: ${{ github.workspace }}
      - name: Deploy site on localhost
        run: |
          cd sources/frontend
          python -m http.server 8080 &
          
          sleep 5
        working-directory: ${{ github.workspace }}
      - name: Install Robot Framework and SeleniumLibrary
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
        working-directory: ${{ github.workspace }}

      - name: Run Chrome Robot Framework Tests
        run: |
          robot -v BROWSER:chrome tests/test.robot
        working-directory: ${{ github.workspace }}
      # - name: Install Firefox
      #   uses: browser-actions/setup-firefox@latest
      # - name: Install Geckodriver
      #   uses: browser-actions/setup-geckodriver@latest
      #   with:
      #     geckodriver-version: '0.34.0'
      # - name: Run Firefox Robot Framework Tests
      #   run: |
      #     robot -v BROWSER:firefox tests/test.robot
      #   working-directory: ${{ github.workspace }}
