name: Robot Framework Tests

on:
  push:
    branches:
      - main

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: docker/compose:1.29.2
        ports:
          - 4444:4444
        options: --entrypoint /usr/local/bin/docker-compose
        env:
          DOCKER_COMPOSE_VERSION: 1.29.2
        volumes:
          - ${{ github.workspace }}:/github/workspace
        container_name: selenium

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Retrieve tests
        run: |
          git clone https://github.com/DevOps-2023-TeamA/tsao-tests.git test_files
          cp -r test_files/frontend/* ${{ github.workspace }}
        working-directory: ${{ github.workspace }}

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 10
        working-directory: ${{ github.workspace }}

      - name: Install Robot Framework and SeleniumLibrary
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
        working-directory: ${{ github.workspace }}

      - name: Run Robot Framework Tests
        run: |
          robot frontend/test.robot
        working-directory: ${{ github.workspace }}

      - name: Tear down Selenium Grid
        run: |
          docker-compose -f docker-compose.yml down
        working-directory: ${{ github.workspace }}
