name: Robot Framework Tests

on:
  push:
    branches:
      - main

jobs:
  selenium_tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: docker/compose:1.29.2
        ports:
          - 4444:4444
        options: --entrypoint /usr/local/bin/docker-compose
        env:
          DOCKER_COMPOSE_VERSION: 1.29.2
        volumes:
          - ${{ github.workspace }}:/github/workspace

    steps:
      - name: Set up directories
        run: |
          mkdir tests
          mkdir sources
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Retrieve tests
        run: |
          git clone https://github.com/DevOps-2023-TeamA/tsao-tests.git tests/alltests
          cp -r tests/alltests/frontend/* tests
        working-directory: ${{ github.workspace }}
      - name: Set up Docker Compose
        run: |
          docker-compose -f tests/docker-compose.yml up -d
          sleep 10
        working-directory: ${{ github.workspace }}
      - name: Deploy site on localhost
        run: |
          cd sources
          python -m http.server 8080 &
          
          sleep 5
        working-directory: ${{ github.workspace }}
      - name: Install Robot Framework and SeleniumLibrary
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
        working-directory: ${{ github.workspace }}

      - name: Run Chrome Robot Framework Tests
        run: |
          robot -v BROWSER:chrome tests/test.robot
        working-directory: ${{ github.workspace }}
      - name: Install Firefox
        uses: browser-actions/setup-firefox@latest

      - name: Install Geckodriver
        uses: browser-actions/setup-geckodriver@v2
        with:
          geckodriver-version: '0.34.0'
      - name: Run Firefox Robot Framework Tests
        run: |
          sudo rm /usr/bin/geckodriver
          robot -v BROWSER:firefox tests/test.robot
        working-directory: ${{ github.workspace }}

      - name: Tear down Selenium Grid
        run: |
          docker-compose -f tests/docker-compose.yml down
        working-directory: ${{ github.workspace }}
