name: Robot Framework Tests

on:
  push:
    branches: [ "main", "actions/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  selenium_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up directories
        run: |
          mkdir tests sources sources/frontend sources/backend sources/db
      - name: "[Database] Checkout code"
        run: |
          git clone https://github.com/DevOps-2023-TeamA/tsao-db.git sources/db
        working-directory: ${{ github.workspace }}
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql root password: root
          mysql database: user
          mysql user: user 
          mysql password: root
      - name: "[Backend] Checkout code"
        run: |
          git clone https://github.com/DevOps-2023-TeamA/tsao-backend-svc.git sources/backend
        working-directory: ${{ github.workspace }}
      - name: "[Backend] Setup Go environment"
        uses: actions/setup-go@v5.0.0
      - name: "[Backend] Deploy Auth Microservice"
        run: |
          cd sources/backend
          go run microservices/auth/auth.go &
        working-directory: ${{ github.workspace }}
      - name: "[Backend] Deploy Users Microservice"
        run: |
          cd sources/backend
          go run microservices/users/users.go &
        working-directory: ${{ github.workspace }}
      - name: "[Backend] Deploy Records Microservice"
        run: |
          cd sources/backend
          go run microservices/records/records.go &
        working-directory: ${{ github.workspace }}
      - name: "[Frontend] Checkout code"
        uses: actions/checkout@v2
        with:
          path: sources/frontend
      - name: "[Frontend] Deploy site on localhost"
        run: |
          cd sources/frontend
          python -m http.server 8080 &
          
          sleep 5
        working-directory: ${{ github.workspace }}
      - name: "[Testing] Retrieve tests"
        run: |
          git clone https://github.com/DevOps-2023-TeamA/tsao-tests.git tests/alltests
          cp -r tests/alltests/frontend/* tests
        working-directory: ${{ github.workspace }}
      - name: "[Testing] Install Robot Framework and SeleniumLibrary"
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
        working-directory: ${{ github.workspace }}

      - name: "[Testing] Run Chrome Robot Framework Tests"
        run: |
          robot -v BROWSER:chrome tests/test.robot
        working-directory: ${{ github.workspace }}
      # - name: Install Firefox
      #   uses: browser-actions/setup-firefox@latest
      # - name: Install Geckodriver
      #   uses: browser-actions/setup-geckodriver@latest
      #   with:
      #     geckodriver-version: '0.34.0'
      # - name: Run Firefox Robot Framework Tests
      #   run: |
      #     robot -v BROWSER:firefox tests/test.robot
      #   working-directory: ${{ github.workspace }}
